version: "3.8"
services:
  postgres:
    image: postgres:15.3-alpine
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres-data:/data/postgres
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_DB=currency_data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  data:

networks:
  default:
    name: currency_network